### ISSUE TITLE
关于post数据的获取和item是编写

### ISSUE THREAD

**Issue by Ehco1996** [gaojiuli/toapi#108]
1. 如果我想解析的一个页面是通过**post请求**才能得到的

请问 toapi 提供这样的方式么？
我看在定义`settings`是有一个参数是`ajax=true`
那么我发送ajax请求的data应该定义在哪里呢？
翻了一圈文档和issues都没找到

2. 关于`items`的编写

自带的`XPath`方法返回的好像是处理过的值而不是一个 `etree element`
这样我比如想要获取h1下所有的文本（包括子标签）就不可以用`string(.)`方法
必须得再写一个`clean_xx`的方法

另外 能否加入bs4的支持呢？

最后希望该项目能越做越好！
真的很棒！

**Comment by howie6879** [comment]
你好 @Ehco1996 
- 关于POST请求请见 #106 ，对于发送ajax请求的data，目前解决是请先用data拼接好形成url在请求，或者自己构建route，然后定义视图函数自己构建，很灵活
- 对于第二点，不是很明白你的意思，想要获取h1下所有的文本（包括子标签）你是指获取html？

**Comment by Ehco1996** [comment]
@howie6879 

谢谢回复

* post的data 和url没有关系吧，我的意思是不知道怎么 通过post方式获得items里的数据

* 第二点： 内置的XPath 方法返回的不是一个标准的 lxml 里的element对象，所以不能直接调用xpath内置的一些方法

**Comment by howie6879** [comment]
你好 @Ehco1996 

- #106 里面的post例子可以解决你的问题么？
- Xpath默认如果元素只有一个会返回text，如果你需要返回etree，可以使用内置的cssselect方式

**Comment by Ehco1996** [comment]
@howie6879 

谢谢回复！

第一问题我看到这样一个代码片段：

```python
api = Api(url)
app = api.server.app

@app.route('/post_page/')
def post_method():
    res = requests.post(url, data) # You need to analysis the ajax post request of source site.
    return  item.parse(res.text)
```

请问这段是需要加在`app.py`里么？
我大概能看懂这是在flask里添加了一个post的路由

可是最后返回的 `item.parse(res.text)` 的item是从哪里来的呢？
还有这个路由是怎么和 `Toapi  Item ` 类发生联动的呢？

* 第二个问题解决了

再次感谢 !

**Comment by howie6879** [comment]
你好 @Ehco1996 
我将用下面的代码片段来解决你说的问题：

``` python
    @api.server.app.route(/post_page/')
    def post_page():
        html = requests.post(url, data) 
        results = {}
        # 定义一个Item列表，意思是你获取的html后，需要按照下面几个你自己定义的Item获取数据
        items = [Item1,Item2]
        for item in items:
            parsed_item = api.parse_item(html, item['item'])
            results[item].__name__] = parsed_item
        return api.server.app.response_class(
            response=json.dumps(results),
            status=200,
            mimetype='application/json'
        )
```

明白了么？

**Comment by Ehco1996** [comment]
@howie6879 
明白了！太感谢了！
