### ISSUE TITLE
Add force-refresh on api

### ISSUE THREAD

**Issue by ahetawal-p** [gaojiuli/toapi#109]
Hello,
I plan to use this awesome tool, to fetch some content from a dynamic website. Although the cache expiration works for standard use cases. 
I was wondering if there is a way on the api to perform a complete fetch from the website instead of using the cache or the storage. A use case would on a mobile device if the user does a `refresh` to see the latest content from the website.

Any ideas ?

Thank you for this...

**Comment by gaojiuli** [comment]
Not support the settings for force-refresh at present. I think this is necessary. I'll add the feature in the future version.
