### ISSUE TITLE
Cache TTL clarification

### ISSUE THREAD

**Issue by creimers** [gaojiuli/toapi#112]
Good evening,

I have a question regarding the cache and its time to live.

Let's say I want to turn some site into an API and want the results of the very first request to be cached for one hour. How would I specify that in the settings? Is such a setup even possible?

I tried setting `ttl: 60 * 60`, assuming that that would do the trick. But to me it seems it doesn't...

Could you please clarify?

Thanks in advance.

**Comment by howie6879** [comment]
Hi @creimers 

How do you set ttl?

``` python
cache = {
        'cache_class': MemoryCache,
        'cache_config': {},
        'serializer': StrSerializer,
        'ttl': 3
    }
```

**Comment by creimers** [comment]
Hey @howie6879 ,

my settings look like this. Pretty much how they came out of the generated project.

```
class MySettings(Settings):

    cache = {
        'cache_class': MemoryCache,
        'cache_config': {},
        'serializer': None,
        'ttl': 60 * 60
    }
    storage = {
        "PATH": os.path.dirname(os.path.abspath(__file__)),
        "DB_URL": None
    }
    web = {
        "with_ajax": False,
        "request_config": {},
        "headers": None
    }

```

**Comment by howie6879** [comment]
Hi @creimers ,
There is no problem with your settings.
I tried setting ttl: 2 * 3, the result is what I want:

``` shell
2018/02/01 08:27:51 [Cache   ] OK Set</one/> 
2018/02/01 08:27:51 [Received] OK http://127.0.0.1:5000/one/ 6216 200 42.69ms 
2018/02/01 08:27:54 [Cache   ] OK Get</one/> 
2018/02/01 08:27:54 [Received] OK http://127.0.0.1:5000/one/ 6216 200 0.20ms 
2018/02/01 08:27:58 [Storage ] OK Get<http://wufazhuce.com/> 
2018/02/01 08:27:58 [Parsed  ] OK Item<Indexone[1]> 
2018/02/01 08:27:58 [Parsed  ] OK Item<Indexarticle[4]> 
2018/02/01 08:27:58 [Parsed  ] OK Item<Indexquestion[4]> 
2018/02/01 08:27:58 [Cache   ] OK Set</one/> 
```

**Comment by creimers** [comment]
Hi. Thanks.

I can confirm that I can reproduce a similar behavior. 

However, it is also the case that the results I get to see after the cache has died and new results are fetched are the same as the cached ones. Even if I know for sure that the data source has changed.

Once I delete the .html folder, I do get updated results. Anything I'm missing here?

**Comment by howie6879** [comment]
Hi, @creimers 

Sorry for the inconvenience, we allow users to set expiration time in storage, it looks like a bit of a problem now.

We will fix this issue quickly. 

Thinks.
