### ISSUE TITLE
Production Deployment Instructions

### ISSUE THREAD

**Issue by ahetawal-p** [gaojiuli/toapi#115]
Hello,
I am relatively new to python web development. And while I am mainly working on a mobile app. I found `topapi` to be a perfect companion for my backend requirements.
I am now almost ready to launch my app, but am struggling to find a good production hosting environment for the `toapi` server code. 
Mainly looking around using `heroku` or `aws` or `google app engine` for hosting server.

I was wondering if you can provide some instructions for deploying to a production quality server. I did go over this [deploy link](http://flask.pocoo.org/docs/0.12/deploying/) but still not able to link the content to the actual toapi codebase.

And advise on how can I move forward with this.

Thank you again,

**Comment by gaojiuli** [comment]
1. Make sure there is 'wsgi.py' in the project root directory.
2. Run 'pip install gunicorn' to install gunicorn
3. Run 'gunicorn -b 127.0.0.1:8080 wsgi:app' , then your backend service is running. Open your browser and visit http://127.0.0.1:8080.
4. Then configure nginx with gunicorn. The article [How to setup Flask with gunicorn and nginx with example](https://tutorials.technology/tutorials/71-How-to-setup-Flask-with-gunicorn-and-nginx-with-examples.html) would help you.

**Comment by howie6879** [comment]
https://github.com/toapi/toapi-search/blob/master/wsgi.py
