### ISSUE TITLE
Error: No such command "new".

### ISSUE THREAD

**Issue by WenHou** [gaojiuli/toapi#120]
[root@test python3]# python --version
Python 3.6.2

[root@test python3]# toapi new toapi/toapi-pic
Usage: toapi [OPTIONS] COMMAND [ARGS]...

Error: No such command "new".

help ?

**Comment by wasnlosdu** [comment]
I'm not sure what you are trying to attempt. Have you read the readme?

Maybe you are trying to create a new project. In that case

```bash
mkdir toapi-pic
cd toapi-pic
pip install toapi
touch app.py
```
and then start coding.

**Comment by pouledodue** [comment]
same issue
see:
https://asciinema.org/a/shet2Ba9d4muCbZ6C3f56EbAt
