### ISSUE TITLE
ImportError: cannot import name 'XPath'

### ISSUE THREAD

**Issue by MARESFAC** [gaojiuli/toapi#121]
XPath去哪啦？？？看起来你好像移除了xpath？？？
![2018-04-27 1 19 28](https://user-images.githubusercontent.com/24603835/39321297-376a3a32-49b9-11e8-8316-962dc0f636ef.png)

**Comment by KurtPrice** [comment]
Why was this closed without any resolution? This seems like a valuable problme to fix.

**Comment by lovetoburnswhen** [comment]
@gaojiuli was XPath removed?
