### ISSUE TITLE
关于资源获取路径路由的问题

### ISSUE THREAD

**Issue by ruter** [gaojiuli/toapi#76]
现在获取资源的链接一般是 `https://yoursite.com/https://targetsite.com/resource/path/`

这样一来会有两个问题：
- 丑，资源请求路径太长，不好看。
- 直接暴露源站。

提出一个设想：

是否可以在 `Meta` 中增加一个 `alias` 作为源站 `base_url` 的替代或标识，并且作为一级资源路径插入到路由中，如 `https://yoursite.com/<alias>/resource/path/`，这样一来既可以满足区分多站点的需求，又可以解决上面提到的两个问题。

在官方仓库中的例子（[查看源码](https://github.com/gaojiuli/toapi/blob/master/examples/dy2018.py)）有利用 `flask` 的路由进行自定义路由的实现，如果有多个站点多个请求路径，这样写在 `items` 里有一份路由，在这里面又要再写一份路由，显得有点机械了。

Thanks.

**Comment by gaojiuli** [comment]
目前我的设想:

```python
class MovieList(Item):
    __base_url = 'http://www.dy2018.com

    url = XPath('//b//a[@class="ulink"]/@href')
    title = XPath('//b//a[@class="ulink"]/text()')

    class Meta:
        source = XPath('//table[@class="tbspan"]')
        route = '/html/gndy/dyzz/index_<page>.html'
        alias = '/movies/?page=<page>'

class Movie(Item):
    __base_url = 'http://www.dy2018.com'

    download = XPath('//*[@id="Zoom"]/table[1]//a/text()')

    class Meta:
        source = None
        alias = '/movies/<id>'
        route = '/i/<id>.html'

class Post(Item):
    __base_url = 'https://news.ycombinator.com'

    url = XPath('//a[@class="storylink"][1]/@href')
    title = XPath('//a[@class="storylink"][1]/text()')

    class Meta:
        source = XPath('//tr[@class="athing"]')
        route = '/news/?p=<page>'
        alias = '/posts/?page=<page>'
```

对外只暴露alias定义的路径, route只作为源站路径. 上面的例子暴露

```
/movies/?page=<page>
/movies/<id>
/posts/?page=<page>
```
``和``和.

路径的定义按照flask route的语法. 这样不但隐藏了源站, 还使得暴露的API接口遵循RESTful风格, 当然, 开发者可以使用任何喜欢的风格.

你觉得这样解决如何?

**Comment by ruter** [comment]
bravo!

一举两得，而且可以更加 RESTful，同时改进源站的路由写法，不用写正则去匹配特殊情况

另外提一点，源站路由用正则可以匹配多种规则的路由，如 `route = '[/search/?q=.+|/page/?p=\d+]'` 可以在一个 item 中匹配路由 `/search` 和 `/page`，如果上面提到的参照 flask route 的源站路由写法能实现，请考虑到这种情况 @gaojiuli

**Comment by gaojiuli** [comment]
这种情况更建议定义为不同的item.

**Comment by ruter** [comment]
今天尝试写实例的时候就遇到这个需求，分别有如下item：
- page 获取next_page
- post 获取page中的所有条目
- search 获取搜索结果

完成上述page和post两个item的编写之后，我在编写对应站点的搜索（search）时发现，搜索结果页的内容和page的是一样的，这样我其实可以直接用page和post而不是重新写一个search item，然后在这个item里写我要获取的page和post，而直接使用page和post的前提就是多路由匹配。

不知道这样描述能不能说清楚问题的关键。

**Comment by gaojiuli** [comment]
明白你的意思。

我那个issue提出的方案应该能兼容你的这个情况。你有什么更好的建议或者更进一步建议么？

**Comment by howie6879** [comment]
@ruter 你完全可以自定义一个search的路由到post和page ，但这个issue https://github.com/gaojiuli/toapi/issues/77 是可以简化操作的，你的search/ 可以关联到page这个item

**Comment by ruter** [comment]
抱歉刚看到前面新开的issue， #77 里的方案确实可以解决我所提出的问题。

另外说一种方案，仅供参考，这是框架 [Odoo](https://github.com/odoo/odoo) 中使用的多路由方案：

只有一个路由的时候是直接写路由路径 `@http.route('/resource/path/<param>', ...)`，多路由的时候是以一个 `list` 的方式 `@http.route(['/resource/foo/<param>', '/resource/bar/<param>'], ...)`

这个 issue 应该可以关闭了 👍

**Comment by gaojiuli** [comment]
他的多路由不存在映射的问题，我们需要映射。
